services:
  vpn:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    volumes:
      - ./profile.ovpn:/opt/openvpn/profile.ovpn:ro
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    network_mode: host
